commit 17-Feb #3

diff --git a/.github/workflows/java-works3.yml b/.github/workflows/java-works3.yml
--- a/.github/workflows/java-works3.yml
+++ b/.github/workflows/java-works3.yml
@@ -1,117 +1,3 @@
-name: Java Playwright CI
-
-on:
-  push:
-    branches: [ main ]
-  pull_request:
-
-jobs:
-  build-test:
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Set up JDK
-        uses: actions/setup-java@v4
-        with:
-          distribution: 'temurin'
-          java-version: '21'
-
-      - name: Cache Maven packages
-        uses: actions/cache@v4
-        with:
-          path: ~/.m2/repository
-          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
-          restore-keys: |
-            ${{ runner.os }}-maven-
-
-      - name: Cache Playwright browsers
-        uses: actions/cache@v4
-        with:
-          path: ~/.cache/ms-playwright
-          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-playwright-
-
-      - name: Install Playwright Browsers
-        if: steps.playwright-cache.outputs.cache-hit != 'true'
-        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install chromium --with-deps"
-        #run: npx playwright install --with-deps
-
-      - name: Build and Test
-        run: mvn clean test
-
-      - name: Upload Allure Results
-        uses: actions/upload-artifact@v4
-        with:
-          name: allure-results
-          path: allure-results
-
-  publish-report:
-    runs-on: ubuntu-latest
-    needs: build-test   # ensures this runs only if build-test succeeds
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Download Allure Results
-        uses: actions/download-artifact@v4
-        with:
-          name: allure-results
-          path: allure-results
-
-#      # Pull history from gh-pages branch if it exists
-#      - name: Checkout gh-pages branch
-#        run: |
-#          git fetch origin gh-pages || echo "No gh-pages branch yet"
-#          if git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
-#            git checkout gh-pages
-#            mkdir -p ../history
-#            cp -r history ../history || true
-#            git checkout -
-#            mkdir -p allure-results/history
-#            cp -r ../history allure-results/ || true
-#          fi
-
-      # Fetch previous gh-pages history
-      - name: Fetch gh-pages history
-        run: |
-            git fetch origin gh-pages || echo "No gh-pages branch yet"
-            if git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
-            git checkout gh-pages
-            mkdir -p ../old-history
-            cp -r history ../old-history || true
-            git checkout -
-            mkdir -p allure-report/history
-            cp -r ../old-history/* allure-report/history/ || true
-            fi
-
-
-      - name: Install Allure CLI
-        run: npm install -g allure-commandline
-
-      - name: Generate Allure Report
-        run: |
-          allure generate allure-results --clean -o allure-report
-
-
-#      - name: Generate Allure Report
-#        run: |
-#          npx allure generate allure-results --clean -o allure-report
-
-      - name: Deploy Allure Report to GitHub Pages
-        uses: peaceiris/actions-gh-pages@v4
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: ./allure-report
-          publish_branch: gh-pages
-          keep_files: true
-
-
-
 #name: Java Playwright CI
 #
 #on:
@@ -120,7 +6,7 @@ jobs:
 #  pull_request:
 #
 #jobs:
-#  build-test-report:
+#  build-test:
 #    runs-on: ubuntu-latest
 #
 #    steps:
@@ -152,27 +38,69 @@ jobs:
 #      - name: Install Playwright Browsers
 #        if: steps.playwright-cache.outputs.cache-hit != 'true'
 #        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install chromium --with-deps"
+#        #run: npx playwright install --with-deps
 #
 #      - name: Build and Test
 #        run: mvn clean test
 #
-#      # Pull history from gh-pages branch
-#      - name: Checkout gh-pages branch
-#        uses: actions/checkout@v4
+#      - name: Upload Allure Results
+#        uses: actions/upload-artifact@v4
 #        with:
-#          ref: gh-pages
-#          path: gh-pages
+#          name: allure-results
+#          path: allure-results
 #
-#      - name: Copy history into allure-results
+#  publish-report:
+#    runs-on: ubuntu-latest
+#    needs: build-test   # ensures this runs only if build-test succeeds
+#
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v4
+#
+#      - name: Download Allure Results
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: allure-results
+#          path: allure-results
+#
+##      # Pull history from gh-pages branch if it exists
+##      - name: Checkout gh-pages branch
+##        run: |
+##          git fetch origin gh-pages || echo "No gh-pages branch yet"
+##          if git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
+##            git checkout gh-pages
+##            mkdir -p ../history
+##            cp -r history ../history || true
+##            git checkout -
+##            mkdir -p allure-results/history
+##            cp -r ../history allure-results/ || true
+##          fi
+#
+#      # Fetch previous gh-pages history
+#      - name: Fetch gh-pages history
 #        run: |
-#          mkdir -p allure-results/history
-#          if [ -d gh-pages/history ]; then
-#            cp -r gh-pages/history allure-results/
-#          fi
+#            git fetch origin gh-pages || echo "No gh-pages branch yet"
+#            if git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
+#            git checkout gh-pages
+#            mkdir -p ../old-history
+#            cp -r history ../old-history || true
+#            git checkout -
+#            mkdir -p allure-report/history
+#            cp -r ../old-history/* allure-report/history/ || true
+#            fi
+#
+#
+#      - name: Install Allure CLI
+#        run: npm install -g allure-commandline
 #
 #      - name: Generate Allure Report
 #        run: |
-#          npx allure generate allure-results --clean -o allure-report
+#          allure generate allure-results --clean -o allure-report
+#
+#
+##      - name: Generate Allure Report
+##        run: |
+##          npx allure generate allure-results --clean -o allure-report
 #
 #      - name: Deploy Allure Report to GitHub Pages
 #        uses: peaceiris/actions-gh-pages@v4
@@ -181,120 +109,192 @@ jobs:
 #          publish_dir: ./allure-report
 #          publish_branch: gh-pages
 #          keep_files: true
-
-
-
-
-
-
-
-
-
-
-
-
-
-#name: Test Java 21 Playwright
-#
-#on:
-#  push:
-#    branches: [ main ]
-#  pull_request:
-#  workflow_dispatch:
 #
 #
-#jobs:
-#  test:
-#    name: Test & Cache (${{ matrix.os }})
-#    runs-on: ${{ matrix.os }}
 #
-#    strategy:
-#      fail-fast: false
-#      matrix:
-#        os: [ubuntu-latest] #, windows-latest, macos-latest]
+##name: Java Playwright CI
+##
+##on:
+##  push:
+##    branches: [ main ]
+##  pull_request:
+##
+##jobs:
+##  build-test-report:
+##    runs-on: ubuntu-latest
+##
+##    steps:
+##      - name: Checkout
+##        uses: actions/checkout@v4
+##
+##      - name: Set up JDK
+##        uses: actions/setup-java@v4
+##        with:
+##          distribution: 'temurin'
+##          java-version: '21'
+##
+##      - name: Cache Maven packages
+##        uses: actions/cache@v4
+##        with:
+##          path: ~/.m2/repository
+##          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+##          restore-keys: |
+##            ${{ runner.os }}-maven-
+##
+##      - name: Cache Playwright browsers
+##        uses: actions/cache@v4
+##        with:
+##          path: ~/.cache/ms-playwright
+##          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
+##          restore-keys: |
+##            ${{ runner.os }}-playwright-
+##
+##      - name: Install Playwright Browsers
+##        if: steps.playwright-cache.outputs.cache-hit != 'true'
+##        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install chromium --with-deps"
+##
+##      - name: Build and Test
+##        run: mvn clean test
+##
+##      # Pull history from gh-pages branch
+##      - name: Checkout gh-pages branch
+##        uses: actions/checkout@v4
+##        with:
+##          ref: gh-pages
+##          path: gh-pages
+##
+##      - name: Copy history into allure-results
+##        run: |
+##          mkdir -p allure-results/history
+##          if [ -d gh-pages/history ]; then
+##            cp -r gh-pages/history allure-results/
+##          fi
+##
+##      - name: Generate Allure Report
+##        run: |
+##          npx allure generate allure-results --clean -o allure-report
+##
+##      - name: Deploy Allure Report to GitHub Pages
+##        uses: peaceiris/actions-gh-pages@v4
+##        with:
+##          github_token: ${{ secrets.GITHUB_TOKEN }}
+##          publish_dir: ./allure-report
+##          publish_branch: gh-pages
+##          keep_files: true
 #
-#    steps:
-#      - name: Checkout code
-#        uses: actions/checkout@v4
-#
-#      - name: Set up Java 21
-#        uses: actions/setup-java@v4
-#        with:
-#          distribution: temurin
-#          java-version: '21'
-#          cache: maven
-#
-#      - name: Cache Playwright Browsers
-#        uses: actions/cache@v4
-#        with:
-#          path: |
-#            ~/.cache/ms-playwright
-#            ~/Library/Caches/ms-playwright
-#            ${{ env.LOCALAPPDATA }}\ms-playwright
-#          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pom.xml') }}
-#          restore-keys: |
-#            ${{ runner.os }}-playwright-
-#
-#      - name: Install Playwright Browsers
-#        if: steps.playwright-cache.outputs.cache-hit != 'true'
-#        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install chromium --with-deps"
 #
 #
-#      - name: Run Tests
-#        run: mvn clean test
 #
 #
-#      - name: Upload Allure Results
-#        if: always()
-#        uses: actions/upload-artifact@v4
-#        with:
-#          name: allure-results-${{ matrix.os }}
-#          path: allure-results
-#          retention-days: 20
 #
-#  publish:
-#    name: Generate & Publish Allure Report
-#    needs: test
-#    runs-on: ubuntu-latest   # publish from a single OS (recommended)
 #
-#    steps:
-#      - name: Checkout repo
-#        uses: actions/checkout@v4
 #
-#      - name: Download Allure Results (Linux)
-#        uses: actions/download-artifact@v4
-#        with:
-#          name: allure-results-ubuntu-latest
-#          path: allure-results
 #
-#      - name: Load Allure History
-#        if: always()
-#        uses: actions/checkout@v4
-#        with:
-#          ref: gh-pages
-#          path: gh-pages
-#        continue-on-error: true
 #
-#      - name: Restore Allure History
-#        if: always()
-#        run: |
-#          mkdir -p allure-results/history
-#          if [ -d "gh-pages/history" ]; then
-#            cp -r gh-pages/history/* allure-results/history/ || true
-#          fi
 #
-#      - name: Generate Allure Report
-#        if: always()
-#        uses: simple-elf/allure-report-action@master
-#        with:
-#          allure_results: allure-results
-#          allure_report: allure-report
-#          gh_pages: gh-pages
-#          keep_reports: 20
 #
-#      - name: Publish Allure Report
-#        if: always()
-#        uses: peaceiris/actions-gh-pages@v4
-#        with:
-#          github_token: ${{ secrets.GITHUB_TOKEN }}
-#          publish_dir: gh-pages
+#
+##name: Test Java 21 Playwright
+##
+##on:
+##  push:
+##    branches: [ main ]
+##  pull_request:
+##  workflow_dispatch:
+##
+##
+##jobs:
+##  test:
+##    name: Test & Cache (${{ matrix.os }})
+##    runs-on: ${{ matrix.os }}
+##
+##    strategy:
+##      fail-fast: false
+##      matrix:
+##        os: [ubuntu-latest] #, windows-latest, macos-latest]
+##
+##    steps:
+##      - name: Checkout code
+##        uses: actions/checkout@v4
+##
+##      - name: Set up Java 21
+##        uses: actions/setup-java@v4
+##        with:
+##          distribution: temurin
+##          java-version: '21'
+##          cache: maven
+##
+##      - name: Cache Playwright Browsers
+##        uses: actions/cache@v4
+##        with:
+##          path: |
+##            ~/.cache/ms-playwright
+##            ~/Library/Caches/ms-playwright
+##            ${{ env.LOCALAPPDATA }}\ms-playwright
+##          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pom.xml') }}
+##          restore-keys: |
+##            ${{ runner.os }}-playwright-
+##
+##      - name: Install Playwright Browsers
+##        if: steps.playwright-cache.outputs.cache-hit != 'true'
+##        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install chromium --with-deps"
+##
+##
+##      - name: Run Tests
+##        run: mvn clean test
+##
+##
+##      - name: Upload Allure Results
+##        if: always()
+##        uses: actions/upload-artifact@v4
+##        with:
+##          name: allure-results-${{ matrix.os }}
+##          path: allure-results
+##          retention-days: 20
+##
+##  publish:
+##    name: Generate & Publish Allure Report
+##    needs: test
+##    runs-on: ubuntu-latest   # publish from a single OS (recommended)
+##
+##    steps:
+##      - name: Checkout repo
+##        uses: actions/checkout@v4
+##
+##      - name: Download Allure Results (Linux)
+##        uses: actions/download-artifact@v4
+##        with:
+##          name: allure-results-ubuntu-latest
+##          path: allure-results
+##
+##      - name: Load Allure History
+##        if: always()
+##        uses: actions/checkout@v4
+##        with:
+##          ref: gh-pages
+##          path: gh-pages
+##        continue-on-error: true
+##
+##      - name: Restore Allure History
+##        if: always()
+##        run: |
+##          mkdir -p allure-results/history
+##          if [ -d "gh-pages/history" ]; then
+##            cp -r gh-pages/history/* allure-results/history/ || true
+##          fi
+##
+##      - name: Generate Allure Report
+##        if: always()
+##        uses: simple-elf/allure-report-action@master
+##        with:
+##          allure_results: allure-results
+##          allure_report: allure-report
+##          gh_pages: gh-pages
+##          keep_reports: 20
+##
+##      - name: Publish Allure Report
+##        if: always()
+##        uses: peaceiris/actions-gh-pages@v4
+##        with:
+##          github_token: ${{ secrets.GITHUB_TOKEN }}
+##          publish_dir: gh-pages
